# Generated by Django 5.2 on 2025-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elderly', '0002_alter_admin_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='assigned_users',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
