# Generated by Django 5.2 on 2025-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elderly', '0003_alter_admin_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='sugar_levels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=10),
        ),
    ]
