# Generated by Django 5.2 on 2025-04-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elderly', '0004_healthrecord_blood_pressure_healthrecord_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('neurologist', 'Neurologist'), ('cardiologist', 'Cardiologist'), ('geriatrician', 'Geriatrician')], max_length=100, null=True),
        ),
    ]
