# Generated by Django 5.2 on 2025-04-14 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elderly', '0006_remove_elderlyuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Elderly.doctor'),
        ),
    ]
