# Generated by Django 5.2 on 2025-04-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elderly', '0007_servicerequest_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderlyuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
